name: 'Bicep Whatif / Deploy'

on:
  push:
    branches:
    - main
    paths:
    - 'IaC/bicep/rg-hub/**'
    - '.github/workflows/bicep-hub.yml'
    
  pull_request:
    branches:
    - main
    paths:
    - 'IaC/bicep/rg-hub/**'
    - '.github/workflows/bicep-hub.yml'

  workflow_dispatch:
  
jobs:
  reusable_workflow_job:
    uses: tjcorr/aks-baseline-automation/.github/workflows/bicep-reusable.yml@main
    with:
      location: "eastus"
      bicep_template: "IaC/bicep/rg-hub/hub-default.bicep"
      bicep_parameters:  "IaC/bicep/rg-hub/hub-default.parameters.json"
      deployment_name: "aks-hub"
    secrets: inherit
