name: 'Bicep Whatif / Deploy'

on:
  push:
    branches:
    - main
    paths:
    - 'IaC/bicep/rg-hub/**'
    - '.github/workflows/bicep-hub.yml'
    
  pull_request:
    branches:
    - main
    paths:
    - 'IaC/bicep/rg-hub/**'
    - '.github/workflows/bicep-hub.yml'

  workflow_dispatch:
  
  
env:
  LOCATION: "eastus"
  BICEP_TEMPLATE: "IaC/bicep/rg-hub/hub-default.bicep"
  BICEP_PARAMETERS: "IaC/bicep/rg-hub/hub-default.parameters.json"
  DEPLOYMENT_NAME: "aks-hub"

jobs:
  reusable_workflow_job:
    uses: tjcorr/aks-baseline-automation/.github/workflows/bicep-reuseable.yml@main
    with:
      location: ${{env.LOCATION}}
      bicep_template: ${{env.BICEP_TEMPLATE}}
      bicep_parameters: ${{env.BICEP_PARAMETERS}}
      deployment_name: ${{env.DEPLOYMENT_NAME}}
